### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by stevevance** [iandees/josm-geojson#2]
I installed it via the Plugins preference pane. I don't see any options to open a GeoJSON feed/file.

**Comment by iandees** [comment]
It's been a few years since I worked on this, but I think it was designed as a file opening adapter. You should be able to select GeoJSON as a file type from the File > Open... dialog and use it to open a GeoJSON document.

Having said that, it probably makes more sense to use `ogr2osm` for this kind of stuff. Is opening GeoJSON still useful? Is the interest in having it as an overlay only, or is the desire to have it show up as a data layer that is editable?

**Comment by stevevance** [comment]
My site Chicago Cityscape has a lot of REST APIs that output GeoJSON. I want to overlay building permits so I can see where new buildings are supposed to have been built. Then I'll confirm with Bing imagery and draw the buildings, getting the address from the permits.

**Comment by stevevance** [comment]
@iandees I used Open Location... and tried to open my GeoJSON feed, not a text file :)

**Comment by stevevance** [comment]
I got this error. The GeoJSON validated in GeoJSONLint.com.
<img width="846" alt="screenshot 2016-03-31 09 08 42" src="https://cloud.githubusercontent.com/assets/1330459/14178418/2f94bdac-f720-11e5-9705-92116a52e694.png">

Here's the GeoJSON:
[permits near 10507 s martin.txt](https://github.com/iandees/josm-geojson/files/197794/permits.near.10507.s.martin.txt)
